### PR TITLE
Upgraded project to RC2

### PR DESCRIPTION
**Pull request by JakeGinnivan**
This will be a new package `IdentityServer3.Integration.AspNetCore` to match the repo and the new package naming in RC2.

This works as well as it did before, no guarantees that everything that needs to be mapped across is, but so far seems all good to me.

### CODE REVIEW

**Comment by leastprivilege** [comment]
thanks!

**Comment by leastprivilege** [comment]
cu next week ;)

**Comment by JakeGinnivan** [comment]
Looking forward to it :)

**Comment by leastprivilege** [comment]
pushed 
https://www.nuget.org/packages/IdentityServer3.Integration.AspNetCore/

**Pull request merged**
