### PR TITLE
Update to .NET Core 1.0.0

### PR DESCRIPTION
**Pull request by IngbertPalm**

### CODE REVIEW

**Comment by leastprivilege** [comment]
thanks!

**Comment by IngbertPalm** [comment]
Is it possible to publish the NuGet package?

**Comment by leastprivilege** [comment]
yes - later.

**Comment by IngbertPalm** [comment]
Thanks!

**Comment by leastprivilege** [comment]
done 

https://www.nuget.org/packages/IdentityServer3.Integration.AspNetCore/

**Pull request merged**
